version: '3.7'
services:
    nginx:
      container_name: nginx
      image: nginx:latest
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
        protocol: tcp
      depends_on:
        - static-website
    static-website:
      container_name: static-website
      image: 
    server:
      container_name: server  
    db-connector:
      container_name: db-connector
    mongo:
      image: mongo
