version: '3.7'
services:
    nginx:
      image: nginx:latest
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
        protocol: tcp
      depends_on:
        - static_website
    static_website:
      image: jmclark/static_website
      build:
        context: ./static_website
        dockerfile: Dockerfile
      depends_on:
      - mongo
      - db_connector
      ports:
      - target: 8089
        published: 8089
        protocol: tcp
      
    mongo:
      image: mongo
    db_connector:
      image: jmclark/db_connector
      build:
        context: ./db_connector
        dockerfile: Dockerfile
      depends_on:
      - mongo
      ports:
      - target: 5001
        published: 5001
        protocol: tcp
    server:
      image: jmclark/server
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
      - target: 8084
        published: 8084
        protocol: tcp
      depends_on:
      - mongo
      - db_connector
    notification_server:
      image: jmclark/notification_server
      build:
        context: ./notification_server
        dockerfile: Dockerfile
      ports:
      - target: 9000
        published: 9000
        protocol: tcp
      depends_on:
      - prize-gen
    prize-gen:
       image: jmclark/prize-gen:v2
       ports:
       - target: 9017
         published: 9017
         protocol: tcp
       depends_on:
       - db_connector
    num-gen:
      image: jmclark/num-gen:v1
      ports:
      - target: 9018
        published: 9018
      depends_on:
      - server
    text-gen:
      image: jmclark/text-gen:v2
      ports:
      - target: 9019
        published: 9019
      depends_on:
      - server
