apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationserver
  labels:
    app: notificationserver
spec:
  selector:
    matchLabels:
      app: notificationserver
  template:
    metadata:
      labels:
        app: notificationserver
    spec:
      containers:
      - name: notificationserver
        image: jmclark/notification_server:latest
        ports:
        - containerPort: 9000
