apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticwebsite
  labels:
    app: staticwebsite
spec:
  selector:
    matchLabels:
      app: staticwebsite
  template:
    metadata:
      labels:
        app: staticwebsite
    spec:
      containers:
      - name: staticwebsite
        image: jmclark/static_website:latest
        ports:
        - containerPort: 8089
